import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import Header from "@/components/fragments/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Toaster />
                    <Header />
                    <div className={"min-h-screen flex flex-col bg-white"}>
                        {children}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
